name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Compose services
        run: docker compose build

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Show running containers
        run: docker ps

      - name: Stop services
        run: docker compose down